name: base
channels:
  - conda-forge
dependencies:
  - nbsphinx
  - nbsphinx-link
  - pydata-sphinx-theme
  - sphinx-copybutton
  - sphinx-favicon
  - pandoc
  - numpy
  - pandas
  - cython
  - docutils==0.21.1
