name: base
channels:
  - conda-forge
dependencies:
  - docutils=0.20
  - nbsphinx
  - nbsphinx-link
  - pydata-sphinx-theme
  - sphinx-copybutton
  - sphinx-favicon
  - pandoc
  - numpy
  - pandas
  - cython
