name: Run Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Change to the version of Python you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pandas numpy cython

    - name: Install optimask
        cython optimask/optimask_cython.pyx
        pip install -e .

    - name: Run Pytest
      run: |
        pytest tests/test_optimask.py
